name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 9, 10, 11]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: "Build Windows"
      if: matrix.os == 'windows-latest'
      run: |
        mvn -f pom-windows.xml clean install
    - name: "Build non-Windows"
      if: matrix.os != 'windows-latest'
      run: |
        mvn clean install

